create table client
(
    id   bigint not null primary key,
    name varchar(50)
);

create table address
(
    id        bigint generated by default as identity,
    street    varchar(255),
    client_id bigint unique,
    primary key (id)
);

create table phone
(
    id        bigint generated by default as identity,
    number    varchar(255),
    client_id bigint,
    primary key (id)
);

alter table if exists address
    add constraint FKp5ipujci6p031lc721y5gaoh7
        foreign key (client_id)
            references client;

alter table if exists phone
    add constraint FKffme64d5dkjig7ytqoif7yi9x
        foreign key (client_id)
            references client;

create sequence client_SEQ start with 1 increment by 1;